name: Go

on:
  push:
    branches: [ delete ]
  pull_request:
    branches: [ delete ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Get dependencies
      run: |
        GO111MODULE=off go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi
    - name: Build
      run: |
           GO111MODULE=off CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -v -o linux_amd64 ./...
           GO111MODULE=off CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -v -o windows_amd64.exe ./...
    - name: Release
      if: startsWith(github.ref, 'refs/tags/') 
      uses: softprops/action-gh-release@v1
      with: # 将下述可执行文件 release 上去
        files: |
            windows_amd64.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: |
          windows_amd64.exe
          linux_amd64
